cost-analyzer:
  global:
    prometheus:
      enabled: false
      fqdn: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
  
  kubecostProductConfigs:
    clusterName: eks-lab-argocd
  
  prometheus:
    server:
      enabled: false
    nodeExporter:
      enabled: false
  
  ingress:
    enabled: false
  
  service:
    type: ClusterIP
