# Values are injected by ArgoCD from Terraform outputs
# See argocd-apps/karpenter.yaml for parameter definitions

karpenter:
  settings:
    clusterName: PLACEHOLDER
    clusterEndpoint: PLACEHOLDER
    interruptionQueue: PLACEHOLDER
  
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: PLACEHOLDER
