# Working Karpenter 1.8.2 Configuration
# Installed in kube-system namespace

settings:
  clusterName: eks-lab-argocd
  clusterEndpoint: https://BE0F3FEABAA778D3BC9205B78F24F8C7.gr7.eu-central-1.eks.amazonaws.com
  interruptionQueue: eks-lab-argocd

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::432801802107:role/KarpenterControllerRole-eks-lab-argocd
